name: Compile & Check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
  workflow_call:

jobs:
  compile:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Compile
      shell: pwsh
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        ./scripts/Compile.ps1
      continue-on-error: false
